---
title: "Gibbs Sampler Example Usages"
output: html_notebook
---

```{r}
library(latex2exp)
library(tidyverse)
source("samplers.R")
```


## Using the Multivariate Normal Gibbs Sampler

```{r}
y_blue <- as.matrix(read.table("data/bluecrab.dat"))
y_orange <-  as.matrix(read.table("data/orangecrab.dat"))

post_blue <- gibbs_mvn(y_blue)
post_orange <- gibbs_mvn(y_orange)

blue_theta_plot <- ggplot(data.frame(post_blue$theta), aes(x = X1, y = X2)) + 
                    geom_point(color = "blue", shape = ".") +
                    labs(x = TeX('$\\theta_1$'), y = TeX('$\\theta_2$')) +
                    ggtitle("Posterior Means for Blue Crab Data")

orange_theta_plot <- ggplot(data.frame(post_orange$theta), aes(x = X1, y = X2)) + 
                    geom_point(color = "orange", shape = ".") +
                    labs(x = TeX('$\\theta_1$'), y = TeX('$\\theta_2$')) +
                    ggtitle("Posterior Means for Orange Crab Data")
grid.arrange(blue_theta_plot, orange_theta_plot, ncol = 2, nrow = 1)
```

## Using the Hierarchical Normal Gibbs Sampler

```{r}
filenames <- sapply(1:8, function(x) paste0("data/school", x, ".dat"))
school_data <- sapply(filenames, scan, quiet = TRUE)

post <- gibbs_hierarchical(school_data, mu_0 = mu_0, gamma_0_sq = 5, 
                           tau_0_sq = tau_0_sq, eta_0 = eta_0, 
                           sigma_0_sq = sig_0_sq, nu_0 = nu_0, num_iter = 1000)
```

## Using the Mixed Effect Logistic Regression Sampler

```{r}
math_data <- read.table("data/mathstandard.dat", header = TRUE)

mu_0 <- matrix(c(-3.462, 0.050), 2, 1)
eta_0 <- 4
Lambda_0 <- matrix(c(10.755, -0.179, -0.179, 0.003), 2, 2)
S_0 <- Lambda_0

posterior <- mh_mixed_logistic(math_data, group = "county", response = "metstandard",
                               mu_0 = mu_0, Lambda_0 = Lambda_0, eta_0 = eta_0, S_0 = S_0)
```

